---
title: "ICE I-213 analysis"
author: "UWCHR"
date: "2025-09-22"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, ggmap, tidygeocoder, sf, rnaturalearth)

```


```{r load_data, message=FALSE, warning=FALSE, include=TRUE}

file <- "sea-i213s-2026-02-13-geocoded.csv"

df <- read_delim(here('analyze', 'input', file), delim='|')

# Source for census estimates: https://www.census.gov/data/tables/time-series/demo/popest/2020s-counties-total.html

pop_wa <- read_delim(here::here("analyze", "input", "co-est2024-pop-53.csv"), delim=',', skip = 3, n_max = 40)

pop_or <- read_delim(here::here("analyze", "input", "co-est2024-pop-41.csv"), delim=',', skip = 3, n_max = 37)

col_names <- c("geographic_area", "april_1_2020_estimates_base", "pop_2020", "pop_2021", "pop_2022", "pop_2023", "pop_2024")

names(pop_wa) <- col_names
names(pop_or) <- col_names

pop_wa <- pop_wa %>% 
  dplyr::select(col_names)

pop_or <- pop_or %>% 
  dplyr::select(col_names)

pop_wa <- pop_wa %>% 
  mutate(geographic_area = str_replace(geographic_area, "\\.", ""),
         geographic_area = str_replace(geographic_area, ", Washington", ""),
         state = "WA")

pop_or <- pop_or %>% 
  mutate(geographic_area = str_replace(geographic_area, "\\.", ""),
         geographic_area = str_replace(geographic_area, ", Oregon", ""),
         state = "OR")

pop <- rbind(pop_wa, pop_or)

pop_long <- pop %>% 
  dplyr::select(-april_1_2020_estimates_base) %>% 
  pivot_longer(cols = starts_with("pop")) %>% 
  mutate(name = as.numeric(str_replace(name, "pop_", ""))) %>% 
  filter(!geographic_area %in% c("Washington", "Oregon"))

pop_2025 <- pop_long %>% 
  filter(name == 2024)

pop_2025$name <- 2025

pop_long <- rbind(pop_long, pop_2025)

```

# Annual arrests per capita


```{r}

dat <- df %>% 
  filter(state %in% c("WA", "OR")) %>% 
  filter(cy >= 2022) %>% 
  group_by(cy, state, county) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  drop_na()

dat_wa <- dat %>% 
  filter(state == "WA") %>% 
  complete(county, cy, fill=list(n=0, state = "WA"))
  
dat_or <- dat %>% 
  filter(state == "OR") %>% 
  complete(county, cy, fill=list(n=0, state = "OR"))

dat <- rbind(dat_wa, dat_or)

annual_arrests_pc <- dat %>% 
  left_join(pop_long, by=c("county" = "geographic_area", "state" = "state", "cy" = "name")) %>% 
  rename(arrests = n,
         pop = value) %>% 
  mutate(arrests_pc = arrests / pop * 100000,
         county_lower = tolower(str_replace(county, " County", "")))

p1 <- annual_arrests_pc %>%
  filter(state == "WA") %>%
  ggplot(aes(x = cy, y = arrests_pc, color = county)) +
  geom_line()

ggplotly(p1)

p2 <- annual_arrests_pc %>%
  filter(state == "OR") %>%
  ggplot(aes(x = cy, y = arrests_pc, color = county)) +
  geom_line()

ggplotly(p2)

write_delim(annual_arrests_pc, here::here('analyze', 'output', 'annual-arrests-per-capita-wa-or-2022-2025.csv'), delim = ",", na='')

```




### Quarterly analysis 2025

```{r}

dat <- df %>% 
  filter(state %in% c("WA", "OR")) %>% 
  filter(cy >= 2022) %>% 
  group_by(cy_quarter, state, county) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  drop_na() %>% 
  mutate(cy_quarter = factor(cy_quarter))

dat_wa <- dat %>% 
  filter(state == "WA") %>% 
  complete(county, cy_quarter, fill=list(n=0, state = "WA"))
  
dat_or <- dat %>% 
  filter(state == "OR") %>% 
  complete(county, cy_quarter, fill=list(n=0, state = "WA"))

dat_2 <- rbind(dat_wa, dat_or) %>% 
  mutate(cy = as.numeric(substr(as.character(cy_quarter), 0, 4)))

quarterly_arrests_pc <- dat_2 %>% 
  left_join(pop_long, by=c("county" = "geographic_area", "state" = "state", "cy" = "name")) %>% 
  rename(arrests = n,
         pop = value) %>% 
  mutate(arrests_pc = arrests / pop * 100000,
         county_lower = tolower(str_replace(county, " County", "")))

write_delim(quarterly_arrests_pc, here::here('analyze', 'output', 'quarterly-arrests-per-capita-wa-or-2022-2025.csv'), delim = ",", na='')

p1 <- quarterly_arrests_pc %>% 
  filter(state == "WA") %>% 
  mutate(county = str_c(county, state, sep = ", ")) %>% 
  ggplot(aes(x = cy_quarter, y = arrests_pc, color = county, group = county)) +
  geom_line()

ggplotly(p1)

p2 <- quarterly_arrests_pc %>% 
  filter(state == "OR") %>% 
  mutate(county = str_c(county, state, sep = ", ")) %>% 
  ggplot(aes(x = cy_quarter, y = arrests_pc, color = county, group = county)) +
  geom_line()

ggplotly(p2)

p3 <- quarterly_arrests_pc %>% 
  mutate(county = str_c(county, state, sep = ", ")) %>% 
  ggplot(aes(x = cy_quarter, y = arrests_pc, color = county, group = county)) +
  geom_line()

ggplotly(p3)


```

```{r arrests_pc_pct_change}

annual_arrests_pc <- annual_arrests_pc %>% 
  group_by(state, county) %>% 
  mutate(prev_n = lag(arrests_pc),
         pct_change = ((arrests_pc - prev_n)/prev_n) * 100 )

quarterly_arrests_pc <- quarterly_arrests_pc %>% 
  group_by(state, county) %>% 
  mutate(prev_n = lag(arrests_pc),
         pct_change = ((arrests_pc - prev_n)/prev_n) * 100 )

p1 <- quarterly_arrests_pc %>% 
  filter(state == "OR") %>% 
  ggplot(aes(x = cy_quarter, y = pct_change, fill = county)) +
  geom_col(position = position_dodge2(preserve = "single"))

ggplotly(p1)

p2 <- quarterly_arrests_pc %>% 
  filter(state == "WA") %>% 
  ggplot(aes(x = cy_quarter, y = pct_change, fill = county)) +
  geom_col(position = position_dodge2(preserve = "single"))

ggplotly(p2)

```

```{r}

dat <- quarterly_arrests_pc %>% 
  mutate(county_state = paste(county, state, sep=", ")) %>% 
  filter(cy_quarter == "2025.4") %>% 
  arrange(desc(arrests_pc))

p1 <- quarterly_arrests_pc %>% 
  mutate(county_state = paste(county, state, sep=", "),
         cy_quarter = str_replace(cy_quarter, "\\.", "Q")) %>% 
  filter(cy == 2025,
         county_state %in% head(dat$county_state, 9)) %>% 
  ggplot(aes(x = cy_quarter, y = arrests_pc)) +
  geom_col() +
  ylab("Arrests per 100,000 pop.") +
  xlab("Calendar quarter") +
  facet_wrap(~county_state) +
  labs(title = "High rates of immigration arrests per capita",
       subtitle = "Top counties by arrests per capita, 2025Q4",
       caption = "I-213 data obtained by UW Center for Human Rights\n2024 population estimate via U.S. census")

p1  

```