---
title: "ICE I-213 analysis"
author: "UWCHR"
date: "2025-09-22"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, readxl, ggmap, tidygeocoder, sf, rnaturalearth)

```


```{r load_data, message=FALSE, warning=FALSE, include=TRUE}

file <- "sea-i213s-2026-02-13-geocoded.csv"

df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  janitor::clean_names() %>% 
  mutate(apprehension_date = as.Date(apprehension_date),
         entry_date = as.Date(entry_date),
         occupation_text = str_to_upper(occupation_text),
         app_ldmk_other_comment_text = str_to_upper(app_ldmk_other_comment_text)) %>% 
  mutate(week = floor_date(apprehension_date, "week", week_start = "Monday"),
         month = floor_date(apprehension_date, "month"),
         cy_quarter = as.factor(quarter(apprehension_date, fiscal_start = 1, with_year=TRUE)),
         fy_quarter = as.factor(quarter(apprehension_date, fiscal_start = 10, with_year=TRUE)),
         fy = substr(quarter(apprehension_date, fiscal_start = 10, with_year = TRUE), 0, 4),
         cy = year (apprehension_date))

pop_wa <- read_delim(here::here("analyze", "input", "co-est2024-pop-53.csv"), delim=',', skip = 3, n_max = 40)

pop_or <- read_delim(here::here("analyze", "input", "co-est2024-pop-41.csv"), delim=',', skip = 3, n_max = 37)

col_names <- c("geographic_area", "april_1_2020_estimates_base", "pop_2020", "pop_2021", "pop_2022", "pop_2023", "pop_2024")

names(pop_wa) <- col_names
names(pop_or) <- col_names

pop_wa <- pop_wa %>% 
  dplyr::select(col_names)

pop_or <- pop_or %>% 
  dplyr::select(col_names)

pop_wa <- pop_wa %>% 
  mutate(geographic_area = str_replace(geographic_area, "\\.", ""),
         geographic_area = str_replace(geographic_area, ", Washington", ""),
         state = "WA")

pop_or <- pop_or %>% 
  mutate(geographic_area = str_replace(geographic_area, "\\.", ""),
         geographic_area = str_replace(geographic_area, ", Oregon", ""),
         state = "OR")

pop <- rbind(pop_wa, pop_or)

```

```{r}

dat <- df %>% 
  filter(state %in% c("WA", "OR")) %>% 
  mutate(apprehension_year = year(apprehension_date))

dat_2024 <- dat %>% 
  filter(apprehension_year == 2024)

pop_2024 <- pop %>% 
  dplyr::select(geographic_area, state, pop_2024)

dat_2024_by_county <- dat_2024 %>% 
  group_by(state, county) %>% 
  summarize(n = n())

dat_2024_by_county_pop <- dat_2024_by_county %>% 
  left_join(pop_2024, by=c("county" = "geographic_area", "state" = "state"))

dat_2024_by_county_pop <- dat_2024_by_county_pop %>% 
  mutate(arrests_pc = n / pop_2024 * 100000)

```

```{r}

dat_2025 <- dat %>% 
  filter(apprehension_year == 2025)

pop_2024 <- pop %>% 
  dplyr::select(geographic_area, state, pop_2024)

dat_2025_by_county <- dat_2025 %>% 
  group_by(state, county) %>% 
  summarize(n = n())

dat_2025_by_county_pop <- dat_2025_by_county %>% 
  left_join(pop_2024, by=c("county" = "geographic_area", "state" = "state"))

dat_2025_by_county_pop <- dat_2025_by_county_pop %>% 
  mutate(arrests_pc = n / pop_2024 * 100000)

```

```{r}

dat_2 <- df %>% 
  filter(state %in% c("WA", "OR")) %>% 
  mutate(apprehension_year = year(apprehension_date)) %>% 
  filter(apprehension_year >= 2022) %>% 
  group_by(apprehension_year, state, county) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  drop_na()

dat_2_wa <- dat_2 %>% 
  filter(state == "WA") %>% 
  complete(county, apprehension_year, fill=list(n=0, state = "WA"))
  
dat_2_or <- dat_2 %>% 
  filter(state == "OR") %>% 
  complete(county, apprehension_year, fill=list(n=0, state = "OR"))

dat_2 <- rbind(dat_2_wa, dat_2_or)

pop_long <- pop %>% 
  dplyr::select(-april_1_2020_estimates_base) %>% 
  pivot_longer(cols = starts_with("pop")) %>% 
  mutate(name = as.numeric(str_replace(name, "pop_", ""))) %>% 
  filter(!geographic_area %in% c("Washington", "Oregon"))

pop_2025 <- pop_long %>% 
  filter(name == 2024)

pop_2025$name <- 2025

pop_long <- rbind(pop_long, pop_2025)

dat_2_pop <- dat_2 %>% 
  left_join(pop_long, by=c("county" = "geographic_area", "state" = "state", "apprehension_year" = "name")) %>% 
  rename(arrests = n,
         pop = value) %>% 
  mutate(arrests_pc = arrests / pop * 100000,
         county_lower = tolower(str_replace(county, " County", "")))

p1 <- dat_2_pop %>% 
  filter(state == "WA") %>% 
  ggplot(aes(x = apprehension_year, y = arrests_pc, color = county)) +
  geom_line()

ggplotly(p1)

p2 <- dat_2_pop %>% 
  filter(state == "OR") %>% 
  ggplot(aes(x = apprehension_year, y = arrests_pc, color = county)) +
  geom_line()

ggplotly(p2)

```



```{r map_wa, echo=TRUE, warning=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <- tools::toTitleCase(as.character(states$ID))

wa <- states %>% 
  filter(ID == "Washington")

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>% 
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>% 
  filter(state == "washington") %>% 
  mutate(state = toupper(substr(state, 1, 2)))

counties$area <- as.numeric(st_area(counties))

counties <- left_join(counties, dat_2_pop, by = c("county" = "county_lower", "state" = "state")) %>% 
  drop_na()

counties <- counties %>%
  filter(apprehension_year == 2025)

counties_rank <- counties %>% 
  arrange(desc(arrests_pc)) %>% 
  head(6)

wa_coords <- coord_sf(xlim = c(-125, -116.5), ylim = c(45, 49.5), expand = FALSE, crs = 4326)

st_crs(wa) <- 4326
st_crs(wa$geom) <- 4326
# st_crs(sites) <- 4326
# st_crs(sites$geometry) <- 4326

m1 <- ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = counties, aes(fill = arrests_pc)) + 
  # geom_sf_label(data = counties_rank, aes(label = str_to_title(county), background = NA), force = 100) +
  scale_fill_viridis_c() +
  wa_coords +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  # facet_wrap(~apprehension_year) +
  labs(title = 'ICE arrests per capita',
       subtitle = "Jan.- Dec. 2025",
       fill = "Arrests per\n100,000",
       caption = "I-213 data obtained by UW Center for Human Rights\n2024 population estimate via U.S. census")

m1

ggsave("../output/wa-ice-pc-2025.png", dpi=300)

```

```{r map_wa, echo=TRUE, warning=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <- tools::toTitleCase(as.character(states$ID))

wa <- states %>% 
  filter(ID == "Washington")

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>% 
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>% 
  filter(state == "washington") %>% 
  mutate(state = toupper(substr(state, 1, 2)))

counties$area <- as.numeric(st_area(counties))

counties <- left_join(counties, dat_2_pop, by = c("county" = "county_lower", "state" = "state")) %>% 
  drop_na()

# counties <- counties %>%
#   filter(apprehension_year == 2025)

counties_rank <- counties %>% 
  arrange(desc(arrests_pc)) %>% 
  head(6)

wa_coords <- coord_sf(xlim = c(-125, -116.5), ylim = c(45, 49.5), expand = FALSE, crs = 4326)

st_crs(wa) <- 4326
st_crs(wa$geom) <- 4326
# st_crs(sites) <- 4326
# st_crs(sites$geometry) <- 4326

m1 <- ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = counties, aes(fill = arrests_pc)) + 
  # geom_sf_label(data = counties_rank, aes(label = str_to_title(county), background = NA), force = 100) +
  scale_fill_viridis_c() +
  wa_coords +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  facet_wrap(~apprehension_year) +
  labs(title = 'ICE arrests per capita',
       subtitle = "Jan.- Dec. 2025",
       fill = "Arrests per\n100,000",
       caption = "I-213 data obtained by UW Center for Human Rights\n2024 population estimate via U.S. census")

m1

# ggsave("../output/wa-ice-pc-2025.png", dpi=300)

```

```{r map_or, echo=TRUE, warning=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <- tools::toTitleCase(as.character(states$ID))

or <- states %>% 
  filter(ID == "Oregon")

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>% 
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>% 
  filter(state == "oregon") %>% 
  mutate(state = toupper(substr(state, 1, 2)))

counties$area <- as.numeric(st_area(counties))

counties <- left_join(counties, dat_2_pop, by = c("county" = "county_lower", "state" = "state")) %>% 
  drop_na()

# counties <- counties %>%
#   filter(apprehension_year == 2025)

or_coords <- coord_sf(xlim = c(-125, -116), ylim = c(41.75, 46.5), expand = FALSE, crs = 4326)

st_crs(or) <- 4326
st_crs(or$geom) <- 4326
# st_crs(sites) <- 4326
# st_crs(sites$geometry) <- 4326

m1 <- ggplot(data = or) +
  geom_sf() +
  geom_sf(data = or, fill = NA) + 
  geom_sf(data = counties, aes(fill = arrests_pc)) + 
  scale_fill_viridis_c() +
  or_coords +
  # theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  facet_wrap(~apprehension_year) +
  labs(title = 'ICE arrests per capita',
       subtitle = "per I-213 forms",
       caption = "I-213 data through mid-Aug. 2025\n2022-2024 population estimates via U.S. census\n2024 estimate used for 2025")

m1

```


```{r map_wa_or, echo=TRUE, warning=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <- tools::toTitleCase(as.character(states$ID))

wa <- states %>% 
  filter(ID %in% c('Washington', 'Oregon'))

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>% 
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>% 
  filter(state %in% c('washington', 'oregon'))  %>% 
  mutate(state = toupper(substr(state, 1, 2)))

counties$area <- as.numeric(st_area(counties))

counties <- left_join(counties, dat_2_pop, by = c("county" = "county_lower", "state")) %>% 
  drop_na()

# counties <- counties %>%
#   filter(apprehension_year == 2025)

pnw_coords <- coord_sf(xlim = c(-125, -116), ylim = c(41.5, 49.5), expand = FALSE, crs = 4326)

st_crs(wa) <- 4326
st_crs(wa$geom) <- 4326
# st_crs(sites) <- 4326
# st_crs(sites$geometry) <- 4326

m1 <- ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = counties, aes(fill = arrests_pc)) + 
  scale_fill_viridis_c() +
  pnw_coords +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  facet_wrap(~apprehension_year, nrow=1) +
  labs(title = 'ICE arrests per capita',
       subtitle = "per I-213 forms",
       caption = "I-213 data through mid-Aug. 2025\n2022-2024 population estimates via U.S. census\n2024 estimate used for 2025")

m1

```

### Quarterly analysis 2025

```{r}

# Need to double check this data constructed correctly

dat_2 <- df %>% 
  filter(state %in% c("WA", "OR")) %>% 
  mutate(apprehension_year = year(apprehension_date),
         apprehension_qtr = quarter(apprehension_date, with_year=TRUE)) %>% 
  filter(apprehension_year >= 2025) %>% 
  group_by(apprehension_qtr, apprehension_year, state, county) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  drop_na()

dat_2_wa <- dat_2 %>% 
  filter(state == "WA") %>% 
  complete(county, apprehension_qtr, fill=list(n=0, state = "WA"))
  
dat_2_or <- dat_2 %>% 
  filter(state == "OR") %>% 
  complete(county, apprehension_qtr, fill=list(n=0, state = "OR"))

dat_2 <- rbind(dat_2_wa, dat_2_or)

pop_long <- pop %>% 
  dplyr::select(-april_1_2020_estimates_base) %>% 
  pivot_longer(cols = starts_with("pop")) %>% 
  mutate(name = as.numeric(str_replace(name, "pop_", ""))) %>% 
  filter(!geographic_area %in% c("Washington", "Oregon"))

pop_2025 <- pop_long %>% 
  filter(name == 2024)

pop_2025$name <- 2025

pop_long <- rbind(pop_long, pop_2025)

dat_2_pop <- dat_2 %>% 
  left_join(pop_long, by=c("county" = "geographic_area", "state" = "state", "apprehension_year" = "name")) %>% 
  rename(arrests = n,
         pop = value) %>% 
  mutate(arrests_pc = arrests / pop * 100000,
         county_lower = tolower(str_replace(county, " County", "")))

p1 <- dat_2_pop %>% 
  mutate(county = str_c(county, state, sep = ", ")) %>% 
  ggplot(aes(x = apprehension_qtr, y = arrests_pc, color = county)) +
  geom_line()

ggplotly(p1)

p2 <- dat_2_pop %>% 
  filter(state == "OR") %>% 
  mutate(county = str_c(county, state, sep = ", ")) %>% 
  ggplot(aes(x = apprehension_qtr, y = arrests)) +
  geom_col() +
  facet_wrap(~county)
  

p2

top_arrests <- dat_2_pop %>% 
  mutate(county_state = str_c(county, state, sep = ", ")) %>% 
  filter(apprehension_qtr == "2025.4") %>% 
  arrange(desc(arrests))

p3 <- dat_2_pop %>% 
  mutate(county_state = str_c(county, state, sep = ", ")) %>% 
  filter(county_state %in% head(top_arrests$county_state, 10)) %>% 
  ggplot(aes(x = apprehension_qtr, y = arrests)) +
  geom_col() +
  facet_wrap(~county_state)
  

p3

```

```{r map_wa_or, echo=TRUE, warning=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <- tools::toTitleCase(as.character(states$ID))

wa <- states %>% 
  filter(ID %in% c('Washington', 'Oregon'))

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>% 
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>% 
  filter(state %in% c('washington', 'oregon'))  %>% 
  mutate(state = toupper(substr(state, 1, 2)))

counties$area <- as.numeric(st_area(counties))

counties <- left_join(counties, dat_2_pop, by = c("county" = "county_lower", "state")) %>% 
  drop_na()

# counties <- counties %>%
#   filter(apprehension_year == 2025)

pnw_coords <- coord_sf(xlim = c(-125, -116), ylim = c(41.5, 49.5), expand = FALSE, crs = 4326)

st_crs(wa) <- 4326
st_crs(wa$geom) <- 4326
# st_crs(sites) <- 4326
# st_crs(sites$geometry) <- 4326

plot_county_pc <- function(data_to_plot) {ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = data_to_plot, aes(fill = arrests_pc)) + 
  scale_fill_viridis_c(limits = c(0, 150)) +
  pnw_coords +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  facet_wrap(~apprehension_qtr, nrow=1) +
  labs(title = 'ICE arrests per capita',
       subtitle = "per I-213 forms",
       caption = "I-213 data through Dec. 2025\n2022-2024 population estimates via U.S. census\n2024 estimate used for 2025")}

p1 <- counties %>% 
  filter(apprehension_qtr == "2025.1") %>% 
  plot_county_pc()

ggsave("../output/2025-1-pc.png")

p2 <- counties %>% 
  filter(apprehension_qtr == "2025.2") %>% 
  plot_county_pc()

ggsave("../output/2025-2-pc.png")

p3 <- counties %>% 
  filter(apprehension_qtr == "2025.3") %>% 
  plot_county_pc()

ggsave("../output/2025-3-pc.png")

p4 <- counties %>% 
  filter(apprehension_qtr == "2025.4") %>% 
  plot_county_pc()

ggsave("../output/2025-4-pc.png")

```

# Discrete arrest sites

```{r}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <-str_to_title(as.character(states$ID))

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>%
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>%
  filter(state %in% c('washington', 'oregon'))

counties$area <- as.numeric(st_area(counties))

sites <- df %>% 
  filter(state %in% c("WA", "OR"),
         apprehension_date >= "2025-01-01") %>% 
  select(long, lat, site_code, cy_quarter) %>% 
  na.omit()

sites <- st_as_sf(sites, coords = c("long", "lat"),
                   crs = 4326, agr = "constant") %>% 
  count(geometry, cy_quarter, site_code)

# wa_coords <- coord_sf(xlim = c(-125, -116.5), ylim = c(41.5, 49.5), expand = FALSE, crs = 4326)
# 
# st_crs(dat) <- 4326
# st_crs(dat$geom) <- 4326
st_crs(sites) <- 4326
st_crs(sites$geometry) <- 4326

plot_cites <- function(data_to_plot) {ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = counties, fill = NA) + 
  geom_sf(data = data_to_plot, shape = 21, color = "black", aes( fill = site_code, size = n), alpha=.7) +
  pnw_coords +
  facet_wrap(~cy_quarter, nrow=1) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  scale_size_continuous(limits = c(1, 1100)) +
  labs(title = 'ICE arrests per quarter',
       subtitle = "per I-213 forms",
       caption = "I-213 data through Dec. 2025")}

p1 <- sites %>%
  filter(cy_quarter == "2025.1") %>% 
  plot_cites

ggsave("../output/2025-1.png")

p2 <- sites %>%
  filter(cy_quarter == "2025.2") %>% 
  plot_cites

ggsave("../output/2025-2.png")

p3 <- sites %>%
  filter(cy_quarter == "2025.3") %>% 
  plot_cites

ggsave("../output/2025-3.png")

p4 <- sites %>%
  filter(cy_quarter == "2025.4") %>% 
  plot_cites

ggsave("../output/2025-4.png")

```

```{r}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <-str_to_title(as.character(states$ID))

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>%
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>%
  filter(state %in% c('washington', 'oregon'))

counties$area <- as.numeric(st_area(counties))

sites <- df %>% 
  filter(state %in% c("WA", "OR"),
         apprehension_date >= "2025-01-01") %>% 
  select(long, lat, site_code, cy_quarter) %>% 
  na.omit()

sites <- st_as_sf(sites, coords = c("long", "lat"),
                   crs = 4326, agr = "constant") %>% 
  count(geometry, cy_quarter, site_code)

wa_coords <- coord_sf(xlim = c(-125, -116.5), ylim = c(41.5, 49.5), expand = FALSE, crs = 4326)
# 
# st_crs(dat) <- 4326
# st_crs(dat$geom) <- 4326
st_crs(sites) <- 4326
st_crs(sites$geometry) <- 4326

plot_cites <- function(data_to_plot) {ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = counties, fill = NA) + 
  geom_sf(data = data_to_plot, aes(color = site_code, size = n), alpha=.5) +
  pnw_coords +
  facet_wrap(~cy_quarter, nrow=1) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  scale_size_continuous(limits = c(1, 1000)) +
  labs(title = 'ICE arrests per quarter',
       subtitle = "per I-213 forms",
       caption = "I-213 data through Dec. 2025")}

p1 <- sites %>%
  filter(cy_quarter == "2025.1") %>% 
  plot_cites

ggsave("../output/2025-1.png")

p2 <- sites %>%
  filter(cy_quarter == "2025.2") %>% 
  plot_cites

ggsave("../output/2025-2.png")

p3 <- sites %>%
  filter(cy_quarter == "2025.3") %>% 
  plot_cites

ggsave("../output/2025-3.png")

p4 <- sites %>%
  filter(cy_quarter == "2025.4") %>% 
  plot_cites

ggsave("../output/2025-4.png")

```

```{r pdx_zoom}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <-str_to_title(as.character(states$ID))

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>%
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>%
  filter(state %in% c('washington', 'oregon'))

counties$area <- as.numeric(st_area(counties))

sites <- df %>% 
  filter(state %in% c("WA", "OR"),
         apprehension_date >= "2025-01-01") %>% 
  select(long, lat, site_code, cy_quarter) %>% 
  na.omit()

sites <- st_as_sf(sites, coords = c("long", "lat"),
                   crs = 4326, agr = "constant") %>% 
  count(geometry, cy_quarter, site_code)

pdx_coords <- coord_sf(xlim = c(-124.5, -120), ylim = c(44.5, 47), expand = FALSE, crs = 4326)
# 
# st_crs(dat) <- 4326
# st_crs(dat$geom) <- 4326
st_crs(sites) <- 4326
st_crs(sites$geometry) <- 4326

plot_cites <- function(data_to_plot) {ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = counties, fill = NA) + 
  geom_sf(data = data_to_plot, aes(color = site_code, size = n), alpha=.5) +
  pdx_coords +
  facet_wrap(~cy_quarter, nrow=1) +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  scale_size_continuous(limits = c(1, 1000)) +
  labs(title = 'ICE arrests per quarter',
       subtitle = "per I-213 forms",
       caption = "I-213 data through Dec. 2025")}

p1 <- sites %>%
  filter(cy_quarter == "2025.4") %>% 
  plot_cites

p1

```


# County by POO arrest

```{r map_wa_or, echo=TRUE, warning=FALSE}

world <- ne_countries(scale = "medium", returnclass = "sf")

states <- st_as_sf(maps::map("state", crs = 4326, plot = FALSE, fill = TRUE))

states <- cbind(states, st_coordinates(st_point_on_surface(states)))
states$ID <- tools::toTitleCase(as.character(states$ID))

wa <- states %>% 
  filter(ID %in% c('Washington', 'Oregon'))

counties <- st_as_sf(maps::map("county", plot = FALSE, fill = TRUE))

counties <- counties %>% 
  separate(col = 'ID', into = c("state", "county"), sep = ",", remove = FALSE) %>% 
  filter(state %in% c('washington', 'oregon'))  %>% 
  mutate(state = toupper(substr(state, 1, 2)))

counties$area <- as.numeric(st_area(counties))

dat <- df %>% 
  count(fy_quarter, state, county, site_code) %>% 
  filter(site_code == "POO") %>% 
  mutate(county_lower = tolower(str_replace(county, " County", "")))

counties <- left_join(counties, dat, by = c("county" = "county_lower", "state")) %>% 
  drop_na()

# counties <- counties %>%
#   filter(apprehension_year == 2025)

pnw_coords <- coord_sf(xlim = c(-125, -116), ylim = c(41.5, 49.5), expand = FALSE, crs = 4326)

st_crs(wa) <- 4326
st_crs(wa$geom) <- 4326
# st_crs(sites) <- 4326
# st_crs(sites$geometry) <- 4326

plot_county_pc <- function(data_to_plot) {ggplot(data = wa) +
  geom_sf() +
  geom_sf(data = wa, fill = NA) + 
  geom_sf(data = data_to_plot, aes(fill = n)) + 
  scale_fill_viridis_c(limits = c(0, 1200)) +
  pnw_coords +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid = element_blank()) +
  labs(title = 'Total arrests by Portland ICE sub-office',
       subtitle = "per I-213 forms",
       caption = "I-213 data through Dec. 2025\n2022-2024 population estimates via U.S. census\n2024 estimate used for 2025")}

p1 <- counties %>% 
  filter(fy_quarter == "2025.1") %>% 
  plot_county_pc()

ggsave("../output/2025-1-poo.png")

p2 <- counties %>% 
  filter(fy_quarter == "2025.2") %>% 
  plot_county_pc()

ggsave("../output/2025-2-poo.png")

p3 <- counties %>% 
  filter(fy_quarter == "2025.3") %>% 
  plot_county_pc()

ggsave("../output/2025-3-poo.png")

p4 <- counties %>% 
  filter(fy_quarter == "2025.4") %>% 
  plot_county_pc()

ggsave("../output/2025-4-poo.png")

p5 <- counties %>% 
  filter(fy_quarter == "2026.1") %>% 
  plot_county_pc()

ggsave("../output/2025-5-poo.png")

```