---
title: "ICE I-213 analysis 2022-2025"
author: "UWCHR"
date: "2026-02-18"
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

```{r setup, message=FALSE, warning=FALSE, include=TRUE}

options(scipen = 1000000)
options(ggplot2.continuous.colour = "viridis")
options(ggplot2.continuous.fill = "viridis")
options(ggplot2.discrete.colour = "viridis")
options(ggplot2.discrete.fill = "viridis")

library(pacman)

p_load(here, tidyverse, zoo, lubridate, ggplot2, plotly, gghighlight, viridis, ggmap, tidygeocoder, sf, rnaturalearth)

every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}

every_2nd_nth = function(n) {
  return(function(x) {x[c(FALSE, rep(TRUE, n - 1))]})
}
```

I-213 forms document a subset of all ICE arrests, and may systematically underrepresent some populations. We recommend caution in interpreting this data without comparison to other sources.

```{r load_data, message=FALSE, warning=FALSE, include=TRUE}

file <- "sea-i213s-2026-02-13-geocoded.csv"

df <- read_delim(here('analyze', 'input', file), delim='|') %>% 
  mutate(apprehension_date = as.Date(apprehension_date),
         entry_date = as.Date(entry_date),
         occupation_text = str_to_upper(occupation_text),
         app_ldmk_other_comment_text = str_to_upper(app_ldmk_other_comment_text),
         week = floor_date(apprehension_date, "week", week_start = "Monday"),
         month = floor_date(apprehension_date, "month"),
         cy_quarter = as.factor(str_replace(quarter(apprehension_date, fiscal_start = 1, with_year=TRUE), "\\.", "Q")),
         fy_quarter = as.factor(quarter(apprehension_date, fiscal_start = 10, with_year=TRUE)),
         fy = substr(quarter(apprehension_date, fiscal_start = 10, with_year = TRUE), 0, 4),
         cy = year(apprehension_date),
         trump = apprehension_date >= "2025-01-20",
         days_since_entry = difftime(apprehension_date, entry_date, units="days"),
         years_since_entry = as.numeric(difftime(apprehension_date, entry_date, units="days"))/365.4,
         age_group = cut(age,
                           breaks = c(0, 18, 25, 40, 60, Inf),
                           right = FALSE))
  
general_caption = "Source: DHS I-213 forms obtained via FOIA\nAnalysis: UW Center for Human Rights"

```

```{r}

poo_2025 <- df %>% 
  filter(apprehension_date >= "2025-01-01",
         site_code == "POO")

poo_2025_county_nationality_per_month <- poo_2025 %>% 
  count(month, county, citizenship_country_descr)

poo_2025_processing_disp_per_month <- poo_2025 %>% 
  count(month, processing_disposition_descr)

write_delim(poo_2025, here::here("analyze", "output", "poo_2025.csv"), delim=',', na="")

write_delim(poo_2025_county_nationality_per_month, here::here("analyze", "output", "poo_2025_county_nationality_per_month.csv"), delim=',', na="")

write_delim(poo_2025_processing_disp_per_month, here::here("analyze", "output", "poo_2025_processing_disp_per_month.csv"), delim=',', na="")

```

```{r}

fdl_2025 <- df %>% 
  filter(apprehension_date >= "2025-01-01",
         site_code == "FDL")

fdl_2025_county_locality_per_month <- fdl_2025 %>% 
  count(month, county, locality)

fdl_2025_county_nationality_per_month <- fdl_2025 %>% 
  count(month, county, citizenship_country_descr)

fdl_2025_processing_disp_per_month <- fdl_2025 %>% 
  count(month, processing_disposition_descr)

write_delim(fdl_2025, here::here("analyze", "output", "fdl_2025.csv"), delim=',', na="")

write_delim(fdl_2025_county_nationality_per_month, here::here("analyze", "output", "fdl_2025_county_nationality_per_month.csv"), delim=',', na="")

write_delim(fdl_2025_county_locality_per_month, here::here("analyze", "output", "fdl_2025_county_locality_per_month.csv"), delim=',', na="")

```
